# app.yaml
runtime: nodejs14
service: default
env: standard
env_variables:
  NAME: "Tom S."
#instance_class: F1
#automatic_scaling:
#  min_idle_instances: automatic
#  max_idle_instances: automatic
#  min_pending_latency: automatic
#  max_pending_latency: automatic
